<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxLYheP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxLYheP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxLYheP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxLYheP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxLYheP\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxLYheP',
    'container.build_id' => 'd5e15ba5',
    'container.build_time' => 1654772244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxLYheP');
