<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfmpnNa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfmpnNa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfmpnNa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfmpnNa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfmpnNa\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfmpnNa',
    'container.build_id' => 'd3a13352',
    'container.build_time' => 1654069246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfmpnNa');
