<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmdS6rU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmdS6rU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHmdS6rU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHmdS6rU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHmdS6rU\App_KernelDevDebugContainer([
    'container.build_hash' => 'HmdS6rU',
    'container.build_id' => 'a4a3534e',
    'container.build_time' => 1654598756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmdS6rU');
